# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-18 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='zip_code',
            field=models.IntegerField(null=True, verbose_name='邮政编码'),
        ),
    ]
