# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-18 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20181118_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='product_count',
            field=models.IntegerField(verbose_name='产品数量'),
        ),
    ]
